// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "common_cells/assertions.svh"

module test_ip_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic
) (
  input clk_i,
  input rst_ni,

  // Below Register interface can be changed
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output test_ip_reg_pkg::test_ip_reg2hw_t reg2hw, // Write
  input  test_ip_reg_pkg::test_ip_hw2reg_t hw2reg, // Read

  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import test_ip_reg_pkg::* ;

  localparam int AW = 4;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;

  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;

  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err ;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [31:0] reg_a_qs;
  logic [31:0] reg_a_wd;
  logic reg_a_we;
  logic [31:0] reg_b_qs;
  logic [31:0] reg_b_wd;
  logic reg_b_we;
  logic [31:0] res_qs;
  logic res_re;

  // Register instances

  // Subregister 0 of Multireg reg_a
  // R[reg_a]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_reg_a (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (reg_a_we),
    .wd     (reg_a_wd),

    // from internal hardware
    .de     (hw2reg.reg_a[0].de),
    .d      (hw2reg.reg_a[0].d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.reg_a[0].q ),

    // to register interface (read)
    .qs     (reg_a_qs)
  );



  // Subregister 0 of Multireg reg_b
  // R[reg_b]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_reg_b (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (reg_b_we),
    .wd     (reg_b_wd),

    // from internal hardware
    .de     (hw2reg.reg_b[0].de),
    .d      (hw2reg.reg_b[0].d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.reg_b[0].q ),

    // to register interface (read)
    .qs     (reg_b_qs)
  );



  // Subregister 0 of Multireg res
  // R[res]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_res (
    .re     (res_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.res[0].d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (res_qs)
  );




  logic [2:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == TEST_IP_REG_A_OFFSET);
    addr_hit[1] = (reg_addr == TEST_IP_REG_B_OFFSET);
    addr_hit[2] = (reg_addr == TEST_IP_RES_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = 1'b0;
    if (addr_hit[0] && reg_we && (TEST_IP_PERMIT[0] != (TEST_IP_PERMIT[0] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[1] && reg_we && (TEST_IP_PERMIT[1] != (TEST_IP_PERMIT[1] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[2] && reg_we && (TEST_IP_PERMIT[2] != (TEST_IP_PERMIT[2] & reg_be))) wr_err = 1'b1 ;
  end

  assign reg_a_we = addr_hit[0] & reg_we & ~wr_err;
  assign reg_a_wd = reg_wdata[31:0];

  assign reg_b_we = addr_hit[1] & reg_we & ~wr_err;
  assign reg_b_wd = reg_wdata[31:0];

  assign res_re = addr_hit[2] && reg_re;

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = reg_a_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[31:0] = reg_b_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = res_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Assertions for Register Interface

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))


endmodule
